apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  ports:
  - name: grpc
    port: 3001
    targetPort: 3001
  selector:
    app: account-service
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  ports:
  - name: grpc
    port: 3002
    targetPort: 3002
  selector:
    app: product-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: account-service
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - image: account-service
        name: server
        ports:
        - containerPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: product-service
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - image: product-service
        name: server
        ports:
        - containerPort: 3002
