apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  ports:
  - port: 3030
    protocol: TCP
    targetPort: 3030
  selector:
    app: account
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  ports:
  - port: 3035
    protocol: TCP
    targetPort: 3035
  selector:
    app: product
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
spec:
  replicas: 10
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - env:
        - name: PORT
          value: "3030"
        image: us-central1-docker.pkg.dev/com-b2allsolution-autolive/microservices/account:latest
        imagePullPolicy: Always
        name: server
        ports:
        - containerPort: 3030
      imagePullSecrets:
      - name: artifact-registry
      serviceAccountName: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  replicas: 10
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - env:
        - name: PORT
          value: "3035"
        image: us-central1-docker.pkg.dev/com-b2allsolution-autolive/microservices/product:latest
        imagePullPolicy: Always
        name: server
        ports:
        - containerPort: 3035
      imagePullSecrets:
      - name: artifact-registry
      serviceAccountName: default
