apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-ms-deployment
  labels:
    app: account-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-ms
  template:
    metadata:
      labels:
        app: account-ms
    spec:
      containers:
        - name: account-ms
          image: account-ms-image
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: account-ms-service
spec:
  selector:
    app: account-ms
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080
      nodePort: 31110
