apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
spec:
  selector:
    matchLabels:
      app: account
  replicas: 5
  template:
    metadata:
      labels:
        app: account
    spec:
      serviceAccountName: default
      imagePullSecrets:
        - name: artifact-registry
      containers:
        - name: server
          image: us-central1-docker.pkg.dev/com-b2allsolution-autolive/microservices/account:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3030
          env:
            - name: PORT
              value: "3030"
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: account-service
# spec:
#   type: ClusterIP
#   selector:
#     app: account
#   ports:
#     - protocol: TCP
#       port: 3030
#       targetPort: 3030

# loadbalancer
apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  type: LoadBalancer
  selector:
    app: account
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030
