apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  selector:
    matchLabels:
      app: product
  replicas: 1
  template:
    metadata:
      labels:
        app: product
    spec:
      serviceAccountName: default
      imagePullSecrets:
        - name: artifact-registry
      containers:
        - name: server
          image: us-central1-docker.pkg.dev/com-b2allsolution-autolive/microservices/product:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3035
          env:
            - name: PORT
              value: "3035"
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: product-service
# spec:
#   type: ClusterIP
#   selector:
#     app: product
#   ports:
#     - protocol: TCP
#       port: 3035
#       targetPort: 3035

apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: LoadBalancer
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 3035
      targetPort: 3035
