name: Deploy Service Order to GCP Run on merge
on:
  push:
    # paths:
    #   - "service-order/**"
    branches:
      - main
jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "deploy"
        run: "npm run deploy"
