name: Deploy pdf-generator to GCR on merge
on:
  workflow_dispatch: # allows for manual invocation
  push:
    paths:
      - pdf-generator/**
    branches:
      - main
jobs:
  build_deploy:
    name: Build
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: pdf-generator
      CPU: 1
      MEMORY: 2Gi
      LOCATION: us-central1
      PROJECT: com-b2allsolution-autolive
      INGRESS: all
    defaults:
      run:
        working-directory: ./${{env.SERVICE_NAME}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - id: auth
        name: Authenticated to GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Submit to Cloud Build
        run: gcloud builds submit --config ./cloudbuild.yaml

      - name: Deploy to Cloud Run
        run: >-
          gcloud run deploy ${{env.SERVICE_NAME}} 
          --image ${{env.LOCATION}}-docker.pkg.dev/${{env.PROJECT}}/microservices/${{env.SERVICE_NAME}}
          --region ${{env.LOCATION}} 
          --cpu ${{env.CPU}} 
          --memory ${{env.MEMORY}} 
          --ingress ${{env.INGRESS}}
