# .github/workflows/gcr-cleaner.yml
name: 'GCR Cleaner'

on:
  schedule:
    - cron: '0 0 */1 * *' # runs daily
  workflow_dispatch: # allows for manual invocation

jobs:
  gcr-cleaner:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # configure based on your registry
      - id: "auth"
        name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GAR_JSON_KEY }}"

      # customize based on the gcr-cleaner flags
      - uses: 'docker://us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli'
        with:
          args: >-
            -repo=us-central1-docker.pkg.dev/com-b2allsolution-autolive/microservices
            -repo=us-central1-docker.pkg.dev/com-b2allsolution-autolive/cloud-run-source-deploy
            -recursive=true
            -keep=2